<?php

define("USERNAME_CONTAINS_WHITESPACE", "USERNAME_CONTAINS_WHITESPACE");
define("USERNAME_ALREADY_TAKEN", "USERNAME_ALREADY_TAKEN");
define("USER_NOT_FOUND", "USER_NOT_FOUND");
define("WRONG_PASSWORD", "WRONG_PASSWORD");
define("SUCCESS", "SUCCESS");