version: "3.8"
services:
  web:
    container_name: web
    build: .
    ports:
      - 8008:80
    depends_on:
      - db
    links:
      - db
    networks:
      - binotify

  db:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - 8080:5432
    hostname: postgres
    restart: always
    networks:
      - binotify
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local

networks:
  binotify:
