version: "3.8"
services:
  web:
    container_name: web
    image: tubes-1:latest
    ports:
      - 8001:80
    depends_on:
      - db
      - phpmyadmin
    networks:
      - binotify

  db:
    container_name: mysql
    image: mysql:latest
    ports:
      - 8002:3306
    restart: always
    networks:
      - binotify
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql
      - ./migrations/init.sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    networks:
      - binotify
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - 8003:80

volumes:
  mysql:
    driver: local

networks:
  binotify:
