version: "3.8"
services:
  web:
    container_name: web
    build: .
    ports:
      - 8008:80
    depends_on:
      - db
    links:
      - db
    networks: 
      - binotify

  db:
    container_name: postgres
    image: postgres:15rc2-alpine3.16
    ports:
      - 8080:5432
    hostname: postgres
    restart: always
    networks:
      - binotify

volumes:
  pgdata:
    driver: local

networks:
  binotify:
