version: "3.9"
services:
  binotify-app-web:
    container_name: binotify-app-web
    image: tubes-1:latest
    hostname: binotify-app-web
    env_file:
      - .env
    ports:
      - 8001:80
    depends_on:
      binotify-app-db:
        condition: service_healthy
      binotify-app-phpmyadmin:
        condition: service_started
    networks:
      - binotify-app
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./upload:/var/www/html/upload
      - ./.htaccess:/var/www/html/.htaccess

  binotify-app-db:
    container_name: binotify-app-db
    image: mysql:latest
    hostname: binotify-app-db
    ports:
      - 8002:3306
    restart: always
    healthcheck:
      test: mysqladmin ping -h localhost -u${MYSQL_USER} -p{MYSQL_PASSWORD}
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - binotify-app
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./php.ini:/usr/local/etc/php/conf.d/init.ini

  binotify-app-phpmyadmin:
    container_name: binotify-app-phpmyadmin
    image: phpmyadmin:latest
    hostname: binotify-app-phpmyadmin
    networks:
      - binotify-app
    environment:
      PMA_HOST: binotify-app-db
    depends_on:
      - binotify-app-db
    ports:
      - 8003:80

volumes:
  mysql:
    driver: local

networks:
  binotify-app:
