version: "3.9"
services:
  web:
    container_name: web
    image: tubes-1:latest
    hostname: web
    env_file:
      - .env
    ports:
      - 8001:80
    depends_on:
      db:
        condition: service_healthy
      phpmyadmin:
        condition: service_started
    networks:
      - binotify
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./upload:/var/www/html/upload

  db:
    container_name: mysql
    image: mysql:latest
    hostname: mysql
    ports:
      - 8002:3306
    restart: always
    healthcheck:
      test: mysqladmin ping -h localhost -u${MYSQL_USER} -p{MYSQL_PASSWORD}
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - binotify
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./php.ini:/usr/local/etc/php/conf.d/init.ini

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    hostname: phpmyadmin
    networks:
      - binotify
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - 8003:80

volumes:
  mysql:
    driver: local

networks:
  binotify:
