<?php

define("DATA_NOT_COMPLETE", "DATA_NOT_COMPLETE");
define("INTERNAL_ERROR", "INTERNAL_ERROR");
define("IMAGE_EXTENSION_NOT_SUPPORTED", "IMAGE_EXTENSION_NOT_SUPPORTED");
define("IMAGE_SIZE_EXCEEDED", "IMAGE_SIZE_EXCEEDED");
define("ALBUM_NOT_FOUND", "ALBUM_NOT_FOUND");
define("SONG_NOT_FOUND", "ALBUM_NOT_FOUND");

define("PASSWORD_DOESNT_MATCH", "PASSWORD_DOESNT_MATCH");
define("USERNAME_CONTAINS_WHITESPACE", "USERNAME_CONTAINS_WHITESPACE");
define("USERNAME_ALREADY_TAKEN", "USERNAME_ALREADY_TAKEN");
define("USER_NOT_FOUND", "USER_NOT_FOUND");
define("WRONG_PASSWORD", "WRONG_PASSWORD");
define("METHOD_NOT_ALLOWED", "METHOD_NOT_ALLOWED");
define("GUEST_LIMIT", "GUEST_LIMIT");
define("INCOMPLETE_QUERY_PARAMS", "INCOMPLETE_QUERY_PARAMS");