<?php

define("DATA_NOT_COMPLETE", "DATA_NOT_COMPLETE");
define("INTERNAL_ERROR", "INTERNAL_ERROR");
define("IMAGE_EXTENSION_NOT_SUPPORTED", "IMAGE_EXTENSION_NOT_SUPPORTED");
define("IMAGE_SIZE_EXCEEDED", "IMAGE_SIZE_EXCEEDED");
define("ALBUM_NOT_FOUND", "ALBUM_NOT_FOUND");